### ISSUE TITLE
Possible improvement Permit2Lib.sol:permit2

### ISSUE THREAD

**Issue by invocamanman** [Uniswap/permit2#154]
I think it could be better instead of check the [`DOMAIN_SEPARATOR` ](https://github.com/Uniswap/permit2/blob/main/src/libraries/Permit2Lib.sol#L78) which some tokens that implement `permit` do not implement like [UNI](https://github.com/Uniswap/governance/blob/master/contracts/Uni.sol).
Check instead the `PERMIT_TYPEHASH` in a very similar behaviour.
In this way  you can support native permit to the tokens that do not support `DOMAIN_SEPARATOR` like `UNI`  ( so overall will be more optimal) and also support other DAI like tokens that support permit, that you see in this [list](https://github.com/yashnaman/tokensWithPermitFunctionList/blob/master/hasDAILikePermitFunctionTokenList.json)

EDIT: Also the `DOMAIN_SEPARATOR` will change in every network, so you should update the `DAI_DOMAIN_SEPARATOR` constant in case of a deployment in different networks, but the `PERMIT_TYPEHASH` won't change ^^

**Comment by MerlinEgalite** [comment]
I agree it would be more general!

**Comment by invocamanman** [comment]
Every single token that i check it implements it, for instance you can check this list [list](https://github.com/yashnaman/tokensWithPermitFunctionList)
It's much more common than the `DOMAIN_SEPARATOR`, which a lot of tokens do not implement like UNI

**Comment by MerlinEgalite** [comment]
Thx for the list!

But all token based on the [ERC20](https://github.com/transmissions11/solmate/blob/main/src/tokens/ERC20.sol) from solmate does not have this getter. It's not publicly exposed on Open Zeppelin's version neither. So I guess, some tokens in the wild might not implement it as well.

Perhaps this can easily be handle using a try/catch system though

**Comment by invocamanman** [comment]
I see!, but ye, my proposal was in a similar behavior like now that a try/catch is being used to check the `DOMAIN_SEPARATOR`, to check `PERMIT_TYPEHASH` instead. For example if i'm not mistaken, since UNI do not implement the `DOMAIN_SEPARATOR` right know the Permit2 is being used, but the native permit of UNI could be used instead ( much more optimal).
I think its better to prioritize the common tokens in the network, and the new ones like WETH10 also implement `PERMIT_TYPEHASH` view function.
In a future i think the best way can be the `https://eips.ethereum.org/EIPS/eip-5267` but for the common use case currently, i think the permit_typehash fits better

**Comment by MerlinEgalite** [comment]
@invocamanman I just created a draft PR #176 if you want to check.

**Comment by transmissions11** [comment]
`PERMIT_TYPEHASH` is not part of any standard whatsoever. It's a relic of DAI and UniswapV2ERC20. While there are quite a few tokens that have implemented it, most of them also implement `DOMAIN_SEPARATOR` **like the EIP-2612 standard _requires_**. Tokens implementing only `PERMIT_TYPEHASH` are in violation of EIP-2612 and are implemented incorrectly. It is sad that a major token like UNI is in-violation of EIP-2612, but either way we loose some token compatibility here (unless you check both which idt we should do for gas reasons) and I think we should stick with `DOMAIN_SEPARATOR` because it's actually mandated by the standard we're targeting and not just a copy-pasta error.

**Comment by snreynolds** [comment]
Going to close in favor of following the EIP-2612 standard as @transmissions11 outlines above!
