### ISSUE TITLE
Staticcall to fallback function burns all gas

### ISSUE THREAD

**Issue by PeterMPhillips** [Uniswap/permit2#159]
On [line 90](https://github.com/Uniswap/permit2/blob/main/src/libraries/Permit2Lib.sol#L90) of Permit2Lib there is an attempt to do a staticcall to get the `DOMAIN_SEPARATOR` value. If the token does not have a `DOMAIN_SEPARATOR`, the call fails and the function falls back to using permit2. However, if the token has a fallback function (such as WETH), all gas sent in the static call gets burned. 

This can have negative effects if a user sets a high gasLimit in their transaction. For example, while testing this function my test environment had a default gas limit equal to the block limit, so the transaction used over 29 million gas.

You can see a similar issue come up in this StackExchange post: https://ethereum.stackexchange.com/questions/96547/high-gas-consumption-when-using-staticcall-on-a-non-view-pure-function

**Comment by marktoda** [comment]
Interesting, thanks for raising! @transmissions11 maybe we should cap the gas for DS check? Beyond just wasting user gas this also borks p2lib for these tokens as fallback to permit2 permit() wouldn't happen

**Comment by transmissions11** [comment]
ah yikes— yes sounds like a gas cap is in order
