### ISSUE TITLE
Small test code bug

### ISSUE THREAD

**Issue by 0xdavinchee** [Uniswap/permit2#164]
`AllowanceTransferTest.t.sol`

`testBatchTransferFromMultiToken`
`startBalanceTo1` is `token0.balanceOf(address0);` - should be: `token1.balanceOf(address0);`
`assertEq(token0.balanceOf(address0), startBalanceTo1 + 1 ** 18);` should be `assertEq(token1.balanceOf(address0), startBalanceTo1 + 1 ** 18);`

tests still pass when corrected

**Comment by marktoda** [comment]
Oops, great catch!
