### ISSUE TITLE
Questions about Nonce Schema Encoding

### ISSUE THREAD

**Issue by hcheng826** [Uniswap/permit2#185]
Regarding to the [documentation](https://docs.uniswap.org/contracts/permit2/reference/signature-transfer#nonce-schema), the encoding of nonce should be `uint248 wordPos` and `uint8 bitPos`. I'm confused why they are all `uint256`s in the [code implementation](https://github.com/Uniswap/permit2/blob/main/src/SignatureTransfer.sol#L142)? Thanks!

**Comment by marktoda** [comment]
See https://github.com/Uniswap/permit2/pull/106, this was a gas improvement because the values dont have to be cleaned/recasted later when used for lookups
