### ISSUE TITLE
What is the rationale for freezing the Solidity version?

### ISSUE THREAD

**Issue by PaulRBerg** [Uniswap/permit2#207]
Using a frozen Solidity version makes it easy to bump into issues when integrating Permit2, e.g. https://github.com/Uniswap/permit2/issues/206

What is the rationale for this design choice? Why not allow any versions greater than or equal to 0.8.17, like this?

```solidity
pragma solidity ^0.8.17;
```

Or like this:

```solidity
pragma solidity >=0.8.17 <=0.9.0;
```

**Comment by wei3erHase** [comment]
perhaps the sol v0.8.17 lobbyists have an angle here...

**Comment by hensha256** [comment]
A solution for this was merged in #225

**Comment by PaulRBerg** [comment]
@hensha256 That PR changed the pragma only in `IPermit2.sol`. This issue is about the wider use of the `=0.8.17` pragma in the non-interface files.
