### ISSUE TITLE
OpenZeppelin Contracts v4 to v5

### ISSUE THREAD

**Issue by lilyanB** [Uniswap/permit2#261]
Hi,
when we import Universal Router as a dependency, it uses the OpenZeppelin 4 version. If we have installed version 5 of OpenZeppelin on our project, then we must also install version 4. As a result, we must have two versions of OpenZeppelin.
I don't know all the project dependencies, but is it possible to upgrade to OpenZeppelin 5?
I can help you if needed

**Comment by hensha256** [comment]
The latest version of UniversalRouter is actually on the `dev` branch, which does use v5 of OZ contracts. The branch will be finalized next week, and will be merged to main then.

**Comment by mfw78** [comment]
May I kindly enquire as to where this `dev` branch is located?
